In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'profile_score', 'lpa'])


In [ ]:
# Define the model
model = Sequential()
model.add(Dense(2, activation="linear", input_dim=2))
model.add(Dense(1, activation="linear"))
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
# Print model summary
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# Train the model
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 5ms/step - loss: 9.8418
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 8.6690
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 7.5481
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 6.4749
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 5.7431
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 4.8912
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 4.1131
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 3.6258
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 3.0861
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 2.5847
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 2.2411
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 1.9508
Epoch 13/75
4/4 [==============================] - 0s 3ms/step - loss: 1.

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.get_weights()

[array([[ 0.20165919,  0.5047874 ],
        [ 0.48666707, -0.20033096]], dtype=float32),
 array([-0.05923316,  0.05986478], dtype=float32),
 array([[ 1.226789],
        [-1.291856]], dtype=float32),
 array([-0.05978569], dtype=float32)]